
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Bash@3
        name: BuildAgentIP
        inputs:
          targetType: 'inline'
          script: |
            ipaddress=$(curl -s http://ipinfo.io/ip)
            echo "##vso[task.setvariable variable=address;isOutput=true;]$ipaddress"
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'ea3f2169-1ea9-4f94-9366-e4dcdd76703b'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Add IP to Key Vault Firewall
            az acr network-rule add   --name crKunpengreilgf24g2be2   --ip-address "$(BuildAgentIP.address)"
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: jgq
          dockerfile: '**/Dockerfile'
          containerRegistry: testjgq
          tags: $(Build.BuildId)